- hosts: all
  become_user: root
  become: yes

  tasks:
    - set_fact:
        auto_remove: "{% if  restart_policy == 'always' %} no {% else %} yes {% endif %}"

    - name: Create docker container and connect to network
      docker_container:
        name: "{{ alias }}"
        image: "{{ registry_ip }}/{{ image_name }}"
        auto_remove: "{{ auto_remove }}"
        command: "{{ command }}"
        env: "{{ env }}"
        restart_policy: "{{ restart_policy }}"
        pull: "{{ pull }}"
        ports: "{{ ports }}"
        exposed_ports: "{{ exposed_ports }}"
        volumes: "{{ volumes }}" 


